### PR TITLE
Added page-up/page-down

### PR DESCRIPTION
**Pull request by davidfetter**
- Changed the named keys to do the named things
- Added basic keymap -- should this be generated from the code somehow?

### CODE REVIEW

**Comment by fiatjaf** [comment]
Does it work?

**Comment by davidfetter** [comment]
I thought I'd gotten it working. It may need more work than I thought. :slightly_frowning_face:

**Comment by fiatjaf** [comment]
Hey, I was just asking, not saying it doesn't work. I didn't test yet, but was going to merge anyway if you answered "yes".

**Comment by fiatjaf** [comment]
It does work.

**Comment by davidfetter** [comment]
Thanks!

**Comment by fiatjaf** [comment]
It's me that should be thanking you!

**Comment by davidfetter** [comment]
Well, the patch had functionality and some docs, but no tests, so I appreciate your forbearance. It looks like upstream has tests, which I'm thinking of ripping off^W^Wusing.

**Comment by fiatjaf** [comment]
This is just a quick hack I did because originally jid advertised itself as a jq tool, but actually it had nothing to do with it.

I'm planning on doing a full rewrite with decent interface, but haven't found time for it yet.

**Comment by davidfetter** [comment]
There's nothing quite so permanent in computing as a `quick hack` ;)

Do you have a sketch of what you have in mind for the next version?

**Comment by fiatjaf** [comment]
Something using https://github.com/jroimartin/gocui which seems very very simple and fast.

And https://github.com/threatgrid/jq-go, if it works.

**Pull request merged**
